### ISSUE TITLE
Influx codec fails to decode payload having multiple lines of influx metrics

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#275]
EDIT (@Licenser): We need to add documentation to the influx codec to hint to using line filters for multi-line messages to prevent issues like below:

**Problem**

It was found that the Influx code fails to decode if the payload has multiple Influx line metrics as part of one single request. For this use case, we are using a udp onramp that receives udp datagrams from upstream and decodes the datagrams using Influx codec. When a single datagram has multiple metrics lines , it fails while parsing the timestamp field at the end of for the first line.

Here is one example.
2020-06-02T20:42:44.703383867+00:00 ERROR tremor_runtime::onramp::prelude - [Codec] Invalid Influx Line Protocol data: ParseIntError(64, Error { code: InvalidDigit, index: 19 })

customer.lookup.get_customer_shard,source=mssql,method=customer_id,app=purest,type=gauge elapsed_time=107.8701171875 1591130564637772032
customer.lookup.get_customer_shard,source=static,method=customer_id,app=purest,type=gauge elapsed_time=0.030029296875 1591130564667566336

In the above example , one udp datagram has two metrics lines. And it fails while parsing the timestamp filed  for first one i.e 1591130564637772032.

**Steps**

1.Set up a udp onramp with Influx codec.
2.Send a udp datagram with multiple lines of metrics.
3. check the Tremor log.

**Possible Solution(s)**

Fix the Influx codec decode function to split the datagram payload into multiple lines and then for each line create the json event. Finally return the array of json events.

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: 0.7.1

**Comment by Licenser** [comment]
Hi, this is by design. The lines pre-processor exists to handle multi line data, have you tried that?

**Comment by anuprout** [comment]
Thanks Heinz.

**Comment by Licenser** [comment]
Glad it was so easy to solve :D! If you don't mind I'll re-open it and move it to a documentation issue since it wasn't clear enough in the docs to prevent you from having issues.

**Comment by anuprout** [comment]
Heinz. After adding the "lines" preprocessor , I am getting the below error for some payloads. 

> 2020-06-03T20:54:12.786805851+00:00 WARN tremor_runtime::preprocessor::lines - Discarded line fragment of length 444 since total length of 17605706 exceeds maximum allowed length of 1048576: "sqlrelay_pool_v2,app=sqlrelay,dc=bo1,host=stores-2p0mtcz.host.bo1,pool_id=bt6.csn_storesitesid,wf_pod_nicename=BO1,type=Local,software=sqrelay,version=sqlrelay-1.0.1-9.el7.centos.wfr.x86_64 open_database_connections=0,opened_database_connections=3338,opened_database_cursors=13446,opened_client_connections=6020,new_cursor_used=34866,cursor_reused=34866,total_queries=34866,total_errors=0,virtual_memory_size_kb=435340,resident_set_size_kb=3856"

Seems like it is a limit set while implementing this pre-processor. 
`"lines" => Ok(Box::new(Lines::new('\n', 1_048_576))),`

**Comment by anupdhml** [comment]
The existing implementation of lines preprocessor targets stream-based onramps like tcp, where we need to chunk incoming data into individual events based on a delimiter, and where we may have to wait for the full event data to come through. This means the lines preprocessor will be buffering incoming data internally, until we hit the delimiter.

https://github.com/wayfair-tremor/tremor-runtime/blob/v0.8.0/src/preprocessor/lines.rs#L140-L144

For your influx udp use-case, this type of behavior is not needed since it is already message-oriented. If the udp payload does not end in a new line character -- which it probably won't when it's holding a single metric -- it will be buffered by the lines preprocessor, and subsequent payloads may also keep being buffered until we hit the delimiter as part of some payload (eg: on udp datagrams containing multiple metrics, separated by newline). And if the configured max line length (1 MB) is exceeded before we hit the delimiter, we see the error message you posted.

What we need here is a simple lines preprocessor that just splits the incoming data into events, without buffering. It would be nice if we could control buffering behavior as part of user-side preprocessor configuration, but preprocessors right now are not flexible in that way (there are plans to make it so in the future). The underlying lines preprocessor implementation is generic though and if we expose buffering as a param when it's initialized, we should be able to define a new simpler lines preprocessor for now.

https://github.com/wayfair-tremor/tremor-runtime/blob/v0.8.0/src/preprocessor.rs#L38-L40

@Licenser In my late-night typing, I may have missed something obvious so if there's other alternatives, do tell us!

**Comment by Licenser** [comment]
I think you covered it :) I expected influx to add a new line to the last metric but if it doesn't that's icky :( 

I wonder what the best solution here is, we could make a special codec that splits newlines and assumes a tailing character. An alternative that seems more comparable is adding a preprocessor that adds data (i.e append a newline).

**Comment by Licenser** [comment]
This is solved by #285
